---
- name: ensure logged in to registry
  become: yes
  docker_login:
    username: "{{ container_registry_user }}"
    password: "{{ container_registry_password }}"
    registry_url: "{{ container_registry }}"

- name: ensure application is started
  become: yes
  docker_compose:
    project_name: "{{ me_project_name }}"
    pull: yes
    definition:
      version: '3.8'
      services:
        app:
          image: "{{ me_container_image }}"
          ports:
            - "8080:80"
  register: output

- name: ensure application is running
  ansible.builtin.assert:
    that:
      - "output.services.app.{{ me_project_name }}_app_1.state.running"

- name: ensure logged out from registry
  become: yes
  docker_login:
    state: absent
    registry_url: "{{ container_registry }}"
