---
stages:
  - lint
  - build
  - registry
  - deploy

include:
  - '/.gitlab-ci/ansible.yml'
  - '/.gitlab-ci/docker.yml'

lint:yaml:
  stage: lint
  image: python:buster
  script: |
    test -f requirements.txt && pip install -r requirements.txt
    yamllint -c .yamllint.yml .
  interruptible: true
  variables:
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  tags:
    - docker

lint:playbook:
  stage: lint
  extends:
    - .ansible-lint

build:me:
  stage: build
  image: jojomi/hugo
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  needs: []
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

registry:me:
  stage: registry
  extends:
    - .docker-registry
  only:
    - master
  needs:
    - build:me

deploy:me:
  stage: deploy
  extends:
    - .ansible-playbook
  only:
    - master
  needs:
    - lint:yaml
    - lint:playbook
    - registry:me
  variables:
    ANSIBLE_INVENTORY: .ansible/inventories/production.yml
    ANSIBLE_PLAYBOOK: .ansible/main.yml
