stages:
  - build
  - registry
  - deploy

build:me:
  stage: build
  image: jojomi/hugo
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

registry:me:
  stage: registry
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - mkdir -p /root/.docker
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout "${CI_REGISTRY}"
    - rm -rf /root/.docker
  only:
    - master
  needs:
    - build:me
  tags:
    - docker-cli
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

deploy:me:
  stage: deploy
  image: python:buster
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${SSH_PRIVATE_KEY}")
    - mkdir -p ~/.ssh
    - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
  script:
    - pip install ansible
    - ansible-playbook -i .ansible/inventories/production.yml .ansible/main.yml
  after_script:
    - rm -rf ~/.ssh
  only:
    - master
  needs:
    - registry:me
  tags:
    - docker
  variables:
    ANSIBLE_REMOTE_USER: "${SSH_USER}"
