---
include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Yaml.gitlab-ci.yml'

lint:yaml:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  extends:
    - .yaml-lint
  needs: []

pages:
  image: jojomi/hugo:latest
  before_script:
    - hugo version
  script:
    - hugo -d public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public
  needs: []
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
