stages:
  - build

build:
  stage: build
  image: jojomi/hugo
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  only:
    - master
