stages:
  - build
  - registry
  - deploy

build:web:
  stage: build
  image: jojomi/hugo
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

registry:web:
  stage: registry
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - mkdir -p /root/.docker
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  after_script:
    - docker logout "${CI_REGISTRY}"
    - rm -rf /root/.docker
  needs:
    - build:web
  tags:
    - docker-cli
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"

deploy:web:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add openssh-client bash rsync
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "${SSH_PRIVATE_KEY}")'
    - mkdir -p ~/.ssh
    - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
  script:
    - rsync -hrvz --delete --exclude=_ -e 'ssh -p 22' public_html/ "${SSH_USER_HOST_LOCATION}"
  after_script:
    - rm -rf ~/.ssh
  needs:
    - build:web
  only:
    - master
