---
stages:
  - lint
  - build
  - registry
  - deploy

include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Docker.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'
  - '/.gitlab-ci/ansible.yml'

# stage: lint

lint:docker:
  stage: lint
  extends:
    - .docker-lint

lint:yaml:
  stage: lint
  extends:
    - .yaml-lint

lint:playbook:
  stage: lint
  extends:
    - .ansible-lint
  variables:
    ANSIBLE_PLAYBOOK: .ansible/main.yml

# stage: build

build:me:
  stage: build
  image: jojomi/hugo
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  needs: []
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

# stage: registry

registry:me:
  stage: registry
  extends:
    - .docker-registry
  only:
    - master
  needs:
    - build:me

# stage: deploy

deploy:me:
  stage: deploy
  extends:
    - .ansible-playbook
  only:
    - master
  needs:
    - lint:yaml
    - lint:playbook
    - registry:me
  variables:
    ANSIBLE_INVENTORY: .ansible/inventories/production.yml
    ANSIBLE_PLAYBOOK: .ansible/main.yml
