---
stages:
  - lint
  - build
  - registry
  - trivy
  - deploy

include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Docker.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'
  - project: 'rahome/trivy-cache'
    ref: main
    file:
      - '/Trivy.gitlab-ci.yml'
  - '/.gitlab-ci/ansible.yml'

# stage: lint

lint:docker:
  stage: lint
  extends:
    - .docker-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

lint:playbook:
  stage: lint
  extends:
    - .ansible-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success
  variables:
    ANSIBLE_PLAYBOOK: .ansible/main.yml

lint:yaml:
  stage: lint
  extends:
    - .yaml-lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

# stage: build

build:me:
  stage: build
  image: jojomi/hugo
  script:
    - hugo version
    - hugo -d public_html
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  needs: []
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

# stage: registry

registry:me:
  stage: registry
  extends:
    - .docker-registry
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - build:me

# stage: trivy

trivy:me:
  stage: trivy
  extends:
    - .trivy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - job: registry:me
      optional: true
      artifacts: false

# stage: deploy

deploy:me:
  stage: deploy
  extends:
    - .ansible-playbook
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - lint:yaml
    - lint:playbook
    - registry:me
    - trivy:me
  variables:
    ANSIBLE_INVENTORY: .ansible/inventories/production.yml
    ANSIBLE_PLAYBOOK: .ansible/main.yml
