---
include:
  - project: 'rahome/gitlab-ci-templates'
    ref: main
    file:
      - '/templates/Checkov.gitlab-ci.yml'
      - '/templates/Docker.gitlab-ci.yml'
      - '/templates/Yaml.gitlab-ci.yml'
  - project: 'rahome/trivy-cache'
    ref: main
    file: '/Trivy.gitlab-ci.yml'

build:me:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  image: hugomods/hugo:exts-0.133.0
  needs: []
  before_script:
    - hugo version
  script:
    - hugo --minify -d public_html
  artifacts:
    paths:
      - public_html
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  tags:
    - docker

build:docker:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  extends:
    - .docker-registry
  needs:
    - job: build:me

test:checkov:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  extends:
    - .checkov-junit
  needs: []
  variables:
    CHECKOV_COMMAND: "-f Dockerfile"

test:docker:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH'
  extends:
    - .docker-lint
  needs: []

test:trivy:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  extends:
    - .trivy
  needs:
    - job: build:docker
      optional: true
      artifacts: false

test:yaml:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  extends:
    - .yaml-lint
  needs: []
