stages:
  - build
  - deploy

build:
  stage: build
  image: jojomi/hugo
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - hugo version
    - hugo -d public_html
  artifacts:
    paths:
      - public_html
    expire_in: 3 hours
  only:
    - master

deploy:
  stage: deploy
  image: debian:buster
  before_script:
    - apt-get update -qq && apt-get install -y -qq openssh-client rsync --no-install-recommends
    - mkdir -p ~/.ssh
    - echo "${SSH_HOST_KEY}" > ~/.ssh/known_hosts
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
  script:
    - rsync -hrvz --delete --exclude=_ -e 'ssh -p 22' public_html/ "${SSH_USER_HOST_LOCATION}"
  after_script:
    - rm -rf ~/.ssh
  only:
    - master
