baseURL = "https://raatiniemi.se/"
languageCode = "en-us"
title = "raatiniemi"
theme = "hugo-coder"

[[menu.main]]
  name = "About"
  weight = 1
  url  = "/about/"

[[menu.main]]
  name = "Thoughts"
  weight = 1
  url  = "/thoughts/"

[author]
  name = "Tobias Raatiniemi"

[params]
  avatarurl = "images/avatar.jpeg"
  info = "Software developer from Sweden"

  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2019

  hidecredits = false
  colorscheme = "auto"

  customCSS = ["css/style.css"]

[[params.social]]
  name = "GitLab"
  icon = "fa fa-gitlab fa-2x"
  weight = 1
  url = "https://gitlab.com/raatiniemi/"

[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 1
  url = "https://social.raatiniemi.me/@tobias"

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/raatiniemi/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://se.linkedin.com/in/tobiasraatiniemi"
