baseURL = "https://raatiniemi.me/"
languageCode = "en-us"
title = "raatiniemi"
theme = "hugo-coder"

[[menu.main]]
  name = "About"
  weight = 1
  url  = "/about"

[[menu.main]]
  name = "Thoughts"
  weight = 1
  url  = "/thoughts/"

[params]
  avatarurl = "images/avatar.jpeg"
  author = "Tobias Raatiniemi"
  info = "Software developer from Sweden"

  hidecredits = false

  custom_css = ["css/style.css"]

[[params.social]]
  name = "GitLab"
  icon = "fab fa-gitlab fa-2x"
  weight = 1
  url = "https://gitlab.com/raatiniemi/"

[[params.social]]
  name = "GitHub"
  icon = "fab fa-github fa-2x"
  weight = 1
  url = "https://github.com/raatiniemi/"

[[params.social]]
  name = "LinkedIn"
  icon = "fab fa-linkedin-in fa-2x"
  weight = 1
  url = "https://se.linkedin.com/in/tobiasraatiniemi"

[[params.social]]
  name = "Docker Hub"
  icon = "fab fa-docker fa-2x"
  weight = 1
  url = "https://hub.docker.com/u/raatiniemi"

[[params.social]]
  name = "Pocket"
  icon = "fab fa-get-pocket fa-2x"
  weight = 1
  url = "https://getpocket.com/@raatiniemi"
