---
- name: ensure that environment is configured
  hosts: web
  tasks:
    - name: ensure logged in to registry
      become: yes
      community.general.docker_login:
        registry_url: "{{ container_registry }}"
        username: "{{ container_registry_user }}"
        password: "{{ container_registry_password }}"

    - name: ensure application is started
      become: yes
      community.general.docker_compose:
        project_name: me
        pull: yes
        definition:
          version: '3.8'
          services:
            web:
              container_name: raatiniemi_me
              image: registry.gitlab.com/rahome/me:latest
              restart: always
              networks:
                - traefik
          networks:
            traefik:
              name: traefik
              external: true
      register: output

    - name: ensure application is running
      ansible.builtin.assert:
        quiet: yes
        success_msg: application is running
        fail_msg: application is not running
        that:
          - "{{ output.services.web.raatiniemi_me.state.running }}"

    - name: ensure logged out from registry
      become: yes
      community.general.docker_login:
        registry_url: "{{ container_registry }}"
        state: absent
  vars:
    container_registry: "{{ lookup('env', 'CI_REGISTRY') }}"
    container_registry_user: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    container_registry_password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
