---
- name: ensure that environment is configured
  hosts: me
  tasks:
    - name: ensure logged in to registry
      become: yes
      community.general.docker_login:
        registry_url: "{{ container_registry }}"
        username: "{{ container_registry_user }}"
        password: "{{ container_registry_password }}"

    - name: ensure application is started
      become: yes
      community.general.docker_compose:
        project_name: me
        pull: yes
        definition:
          version: '3.8'
          services:
            app:
              image: "{{ container_registry }}/rahome/me:latest"
              ports:
                - "8080:80"
              restart: always
      register: output

    - name: ensure application is running
      ansible.builtin.assert:
        that:
          - "output.services.app.me_app_1.state.running"

    - name: ensure logged out from registry
      become: yes
      community.general.docker_login:
        registry_url: "{{ container_registry }}"
        state: absent
  vars:
    container_registry: "{{ lookup('env', 'CI_REGISTRY') }}"
    container_registry_user: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    container_registry_password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
