---
- name: ensure that environment is configured
  hosts: web
  roles:
    - web
  vars:
    container_registry: "{{ lookup('env', 'CI_REGISTRY') }}"
    container_registry_user: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    container_registry_password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
